name: restic-server
base: core24
version: '0.14.0'
summary: REST server backend for Restic
description: |
  This snap packages the REST server backend for Restic.

  **Configuration and Daemon Management**

  To simplify management of the REST server daemon, a configuration file (`rest-server.conf`) is provided in the snap package. This file allows you to easily customize the behavior of the REST server without modifying the wrapper script or service definition.

  **Location**

  The configuration file is located at:

   `/snap/restic-server/current/snap/local/rest-server.conf`

  **Usage**

  1. Edit the configuration file to set your desired options (such as data directory, authentication, TLS, etc.).
  2. After making changes, restart the daemon to apply the new configuration:

       `sudo snap restart restic-server`

  The wrapper script (`rest-server-wrapper.sh`) automatically loads and applies the settings from `rest-server.conf` when starting the REST server.

  This approach makes it easy to manage and update the service configuration, ensuring changes are persistent and straightforward.
  distributions.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

platforms:
  amd64:
  arm64:

apps:
  restic-server:
    command: snap/local/rest-server-wrapper.sh
    daemon: simple
    restart-condition: always
    plugs:
      - network
      - network-bind
      - home
      - removable-media

parts:
  rest-server:
    plugin: dump
    source: https://github.com/restic/rest-server/releases/download/v$CRAFT_PROJECT_VERSION/rest-server_$CRAFT_PROJECT_VERSION_linux_$CRAFT_ARCH_BUILD_FOR.tar.gz
    source-type: tar
    override-pull: |
      snapcraftctl pull
      chmod +x rest-server
    organize:
      rest-server: bin/rest-server

  rest-server-wrapper:
    plugin: dump
    source: snap/local/
    override-pull: |
      craftctl default
      chmod +x rest-server-wrapper.sh
    organize:
      rest-server-wrapper.sh: snap/local/rest-server-wrapper.sh
      rest-server.conf: snap/local/rest-server.conf
