name: restic-server
base: core24
version: '0.14.0'
summary: REST server backend for Restic
description: |
  This snap packages the REST server backend for Restic.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: amd64
    build-for: amd64
  - build-on: arm64
    build-for: arm64
  - build-on: armhf
    build-for: armhf
  - build-on: ppc64el
    build-for: ppc64el
  - build-on: s390x
    build-for: s390x

apps:
  restic-server:
    command: snap/local/rest-server-wrapper.sh
    daemon: simple
    restart-condition: always
    plugs:
      - network
      - network-bind
      - removable-media

parts:
  rest-server:
    plugin: dump
    source: https://github.com/restic/rest-server/releases/download/v$CRAFT_PROJECT_VERSION/rest-server_$CRAFT_PROJECT_VERSION_linux_$CRAFT_ARCH_BUILD_FOR.tar.gz
    source-type: tar
    override-pull: |
      snapcraftctl pull
      chmod +x rest-server
    organize:
      rest-server: bin/rest-server

  rest-server-wrapper:
    plugin: dump
    source: snap/local/
    override-pull: |
      craftctl default
      chmod +x rest-server-wrapper.sh
    organize:
      rest-server-wrapper.sh: snap/local/rest-server-wrapper.sh
      rest-server.conf: snap/local/rest-server.conf
